CREATE DATABASE IF NOT EXISTS LB08;

CREATE TABLE IF NOT EXISTS LB08.documentos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    data VARCHAR(255) NOT NULL
);

INSERT INTO LB08.documentos (data) VALUES ('Gustavo Lima!');
